name: "Downloads file"
description: "Downloads file with curl from URL provided"
inputs:
  url:
    description: "URL to call curl against"
    required: true
  filename:
    description: "Output filename"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.url }}
    - ${{ inputs.filename }}
